// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrnfybpbefqdfdactvkw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhybmZ5YnBiZWZxZGZkYWN0dmt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzNjgwNzgsImV4cCI6MjA1NDk0NDA3OH0.FHy0Uvd_B_IayYU3uyL3UAqGnypvmlQJ3NSDwHtG5Ms";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
